version: "3"
services:

  node-app:
    container_name: appcon
    image: anas99anas/node-app
    ports:
     - "4000:4000"
    env_file:
     - ./.env
    depends_on:
     - redis
     
     
  mongo:
    image: mongo
    container_name: mongocon
    volumes:
     - mongo-db:/data/db
    ports:
     - "27017:27017"
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    
  # mongo-express:
  #   image: mongo-express
  #   container_name: mongoexpcon
  #   restart: always
  #   ports:
  #     - 8081:8081
  #   environment:
  #     ME_CONFIG_MONGODB_ADMINUSERNAME: root
  #     ME_CONFIG_MONGODB_ADMINPASSWORD: example
  #     ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
  #   depends_on:
  #    - mongo
  
  
  redis:
    image: redis
    container_name: rediscon
   
  
  nginx:
    image: nginx:stable-alpine
    container_name: nginxcon
    volumes:
    - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
    - "80:80"
    depends_on:
     - node-app
  
  # postgres:
  #   image: postgres
  #   container_name: postcon
  #   volumes:
  #    - postgres-db:/var/lib/postgresql/data
  #   restart: always
  #   environment:
  #     POSTGRES_USER: root
  #     POSTGRES_PASSWORD: example


volumes:
  mongo-db:
  postgres-db:
  